version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "xenon231tech"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-scope: "deps"
      include: "scope"
